/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jFAdicionaProduto.java
 *
 * Created on 21/11/2010, 20:31:13
 */
package restaurantepoo.forms;

import java.security.acl.Owner;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import restaurantepoo.dao.ProdutoDao;
import restaurantepoo.logica.Mesa;
import restaurantepoo.logica.Produto;

/**
 *
 * @author Antonio
 */
public class jFAdicionaProduto extends javax.swing.JFrame {

    /** Creates new form jFAdicionaProduto */
    public  jFAdicionaProduto(jFMesas owner, int numeroMesa) {
        initComponents();
        //this.son = owner;
        m1 = owner.mesas.get(numeroMesa-1);     // posição da mensa no array é seu numero -1
        System.out.println(m1.toString());

    }
    DefaultTableModel tmProduto = new DefaultTableModel(
            new Object[][]{},
            new String[]{"produto", "nome", "preco"}
    );

    private List<Produto> produtos;
    Mesa m1;
    jFMesas son;
    Produto p = new Produto();
    ListSelectionModel lsmProduto;



    private void populaTabela(String busca) throws SQLException {
        ProdutoDao pd = new ProdutoDao();
        produtos = pd.getLista("%" + busca + "%");

        for (Produto p1 : produtos) {
            insereTabela(p1);
        }
    }

    private void insereTabela(Produto p1) {

        tmProduto.addRow(new String[]{
                    String.valueOf(p1.getProduto()),
                    p1.getNome(),
                    String.valueOf(p1.getPreco())
                });
    }

    private void limparCampos() {
        quantidade.setText("");
        codigo.setText("");
    }

    private boolean verificaStrings() {

        if (!codigo.getText().equals("") && !quantidade.getText().equals("")) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Campos obrigatórios não preenchidos");
            return false;
        }
    }

    private boolean verificaInteiro() {
        int temp;
        try {
            temp = Integer.parseInt(quantidade.getText());
            temp = Integer.parseInt(codigo.getText());
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Campos código e quantidade devem ser inteiros");
            return false;
        }
    }

    private void escolherLinha() {

        int linha = tabelaProdutos.getSelectedRow();

        String temp;

        temp = String.valueOf(tabelaProdutos.getValueAt(linha, 0));
        p.setProduto(Integer.parseInt(temp));

        codigo.setText(String.valueOf(p.getProduto()));

    }

    private void populaObjeto(Produto p1) {
        
        p1.setProduto(Integer.parseInt(codigo.getText()));

        try {
            ProdutoDao dao = new ProdutoDao();
            dao.busca(p1);
        } catch (SQLException ex) {
            Logger.getLogger(jFCadProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        campoBusca = new javax.swing.JTextField();
        inserir = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        quantidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 90, 30));

        tabelaProdutos.setModel(tmProduto);
        tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 530, 230));

        campoBusca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(campoBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 240, 20));

        inserir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inserir.setText("Inserir");
        inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirActionPerformed(evt);
            }
        });
        jPanel1.add(inserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 90, 30));

        voltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel1.add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 80, 30));

        quantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 60, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Quantidade:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Busca por Produtos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Código:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        codigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 60, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        try {
            tmProduto.setNumRows(0);
            populaTabela(campoBusca.getText());
        } catch (SQLException ex) {
            Logger.getLogger(jFAdicionaProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void tabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosMouseClicked
        escolherLinha();
    }//GEN-LAST:event_tabelaProdutosMouseClicked

    private void inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirActionPerformed
        if (verificaStrings() && verificaInteiro()) {
            populaObjeto(p);

            for (int i = 0; i < Integer.parseInt(quantidade.getText()); i++) {
                m1.addProduto(p);
            }

            System.out.println(m1.toString());
        }
    }//GEN-LAST:event_inserirActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
//        son.calculaValorTotal();
//        System.out.println("Valor total recalculado: " + m1.getValorTotal());
//
//        try {
//            son.populaTabelaMesas("");
//        } catch (SQLException ex) {
//            Logger.getLogger(jFAdicionaProduto.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ParseException ex) {
//            Logger.getLogger(jFAdicionaProduto.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        son.populaTabelaProdutos(m1);
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JTextField codigo;
    private javax.swing.JButton inserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField quantidade;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

}
