/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jFMesas.java
 *
 * Created on 21/11/2010, 15:16:19
 */

package restaurantepoo.forms;

import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import restaurantepoo.dao.MesaDao;
import restaurantepoo.logica.Mesa;
import restaurantepoo.logica.Produto;

/**
 *
 * @author Antonio
 */
public class jFMesas extends javax.swing.JFrame {

    /** Creates new form jFMesas */
    public jFMesas() throws SQLException, ParseException {
        initComponents();
        populaTabelaMesas("");
        criaMesas(10);
    }
    
     DefaultTableModel tmMesa = new DefaultTableModel(
            new Object [][]{
            },
            new String[]{"mesa", "horaabertura", "valortotal"}
     );
     
     DefaultTableModel tmProduto = new DefaultTableModel(
            new Object [][]{
            },
            new String[]{"produto", "nome", "preco"}
     );

    private List<Mesa> mesas;
    ListSelectionModel lsmMesa;
    ListSelectionModel lsmProdutos;

    private void populaTabelaMesas(String busca) throws SQLException, ParseException{

        MesaDao pd = new MesaDao();
        mesas = pd.getLista("%"+busca+"%");

        for (Mesa p1 : mesas) {
            insereTabelaMesas(p1);
        }

    }
     
     private void populaTabelaProdutos(){

        Mesa m1 = new Mesa();
        m1 = mesas.get(Integer.parseInt(mesa.getText()));

        for (Produto p1 : m1.produtos) {
            insereTabelaProdutos(p1);
        }
    }

    private void insereTabelaMesas(Mesa m1){

        tmMesa.addRow(new String[]{
            String.valueOf(m1.getMesa()),
            !m1.isStatus()?"Livre":String.valueOf(m1.getHoraAbertura()),
            String.valueOf(m1.getValorTotal())
        });
    }

    private void insereTabelaProdutos(Produto p1){

        tmMesa.addRow(new String[]{
            String.valueOf(p1.getProduto()),
            p1.getNome(),
            String.valueOf(p1.getPreco())
        });
    }

    private void criaMesas(int n){
        for (int i=0; i<n; i++){
            Mesa m = new Mesa();
            m.setMesa(i);
            mesas.add(m);
        }
    }

    private void escolherLinha(){

        int linha = tabelaMesas.getSelectedRow();
        //System.out.println(linha);

        String temp;

        temp = String.valueOf(tabelaMesas.getValueAt(linha, 0));
        mesa.setText(temp);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        cadProduto = new javax.swing.JButton();
        mesa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cadFuncionario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMesas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("MESA:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jPanel1.add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 80, 30));

        cadProduto.setText("Cadastrar Produto");
        cadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(cadProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, 30));

        mesa.setEditable(false);
        jPanel1.add(mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 60, -1));

        jTable1.setModel(tmProduto);
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 210));

        cadFuncionario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cadFuncionario.setText("Cadastrar Funcionário");
        jPanel1.add(cadFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, 30));

        jButton1.setText("Fechar Mesa");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 130, 30));

        jButton2.setText("Dividir Conta");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 130, 30));

        jButton3.setText("Adicionar Produto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 370));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabelaMesas.setModel(tmMesa);
        tabelaMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMesasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaMesas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 340, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void cadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadProdutoActionPerformed
        try {
            new jFCadProduto().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(jFMesas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cadProdutoActionPerformed

    private void tabelaMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMesasMouseClicked
        //habilitaDados();
        escolherLinha();
        populaTabelaProdutos();
//        editar.setEnabled(true);
//        excluir.setEnabled(true);
//        salvar.setEnabled(false);
    }//GEN-LAST:event_tabelaMesasMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new jFAdicionaProduto(mesas.get(Integer.parseInt(mesa.getText()))).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadFuncionario;
    private javax.swing.JButton cadProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mesa;
    private javax.swing.JButton sair;
    private javax.swing.JTable tabelaMesas;
    // End of variables declaration//GEN-END:variables

}
