/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jFNotaProduto.java
 *
 * Created on 01/12/2010, 03:00:44
 */

package restaurantepoo.forms;

import java.sql.SQLException;
import restaurantepoo.dao.MesaProdutoDao;
import restaurantepoo.logica.Mesa;

/**
 *
 * @author Fernanda
 */
public class jFNotaProduto extends javax.swing.JFrame {

    /** Creates new form jFNotaProduto */
    public jFNotaProduto(String numMesa) throws SQLException {
        initComponents();
        montaNota(numMesa);
    }

    public void populaTabelaProdutosBanco() throws SQLException {
        tmProduto.setRowCount(0);

        MesaProdutoDao dao = new MesaProdutoDao();
        Mesa m1 = new Mesa();
        Double somaTotal = 0.0;

        dao.getListaProdutosMesa(numeroMesa.getText(), m1);

        for (int i = 0; i < m1.produtos.size(); i++) {

            double preco = m1.produtos.get(i).getPreco();
            int qtd = Integer.parseInt(m1.quantidade.get(i));
            Double soma = qtd*preco;
            somaTotal += soma;

            tmProduto.addRow(new String[]{
                        String.valueOf(m1.produtos.get(i).getProduto()),
                        m1.produtos.get(i).getNome(),
                        String.valueOf(preco),
                        String.valueOf(qtd),
                        String.valueOf(soma)
                    });
        }
        salvaValorTotal(somaTotal);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nota Fiscal Produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFNotaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
