/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jTFuncionario.java
 *
 * Created on 10/11/2009, 00:49:25
 */

package restaurante.forms;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import restaurante.dao.IngredienteDao;
import restaurante.logica.Ingrediente;

/**
 *
 * @author Fernanda
 */
public class jFCadIngrediente extends javax.swing.JFrame {

    /** Creates new form jTFuncionario */
    public jFCadIngrediente() throws SQLException {
        
        initComponents();
        populaTabela("");
        desabilitaDados();
        desabilitarVisaoTodos();
    }

    DefaultTableModel tmIngrediente = new DefaultTableModel(
            new Object [][]{
            },
            new String[]{"id", "nome","marca","estoque"});
    
    private List<Ingrediente> ingredientes;
    ListSelectionModel lsmIngrediente;

    public void populaTabela(String busca) throws SQLException{

        IngredienteDao fd = new IngredienteDao();
        ingredientes = fd.getLista("%"+busca+"%");
        
        for (Ingrediente i1 : ingredientes) {
            insereTabela(i1);
        }
    }

    public void insereTabela(Ingrediente i1){

        tmIngrediente.addRow(new String[]{
            String.valueOf(i1.getId()),
            i1.getNome(),
            i1.getMarca(),
            String.valueOf(i1.getEstoque()),
        });
    }




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCadFuncionario = new javax.swing.JPanel();
        jPPesquisaNome = new javax.swing.JPanel();
        jBPesquisa = new javax.swing.JButton();
        jTPesquisa = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLID = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jLMarca = new javax.swing.JLabel();
        jLEstoque = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jTNome = new javax.swing.JTextField();
        jTMarca = new javax.swing.JTextField();
        jTEstoque = new javax.swing.JTextField();
        jBSalvar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jBSair = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTIngrediente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(354, 124, 600, 600));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 255));
        setIconImages(null);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPCadFuncionario.setBackground(new java.awt.Color(102, 255, 204));
        jPCadFuncionario.setAlignmentX(0.0F);
        jPCadFuncionario.setAlignmentY(0.0F);
        jPCadFuncionario.setPreferredSize(new java.awt.Dimension(600, 600));

        jPPesquisaNome.setBackground(new java.awt.Color(255, 255, 255));
        jPPesquisaNome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa pelo Nome do Ingrediente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPPesquisaNome.setPreferredSize(new java.awt.Dimension(580, 61));

        jBPesquisa.setText("Pesquisa");
        jBPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisaActionPerformed(evt);
            }
        });

        jTPesquisa.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jPPesquisaNomeLayout = new javax.swing.GroupLayout(jPPesquisaNome);
        jPPesquisaNome.setLayout(jPPesquisaNomeLayout);
        jPPesquisaNomeLayout.setHorizontalGroup(
            jPPesquisaNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPesquisaNomeLayout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(jTPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPesquisa)
                .addGap(24, 24, 24))
        );
        jPPesquisaNomeLayout.setVerticalGroup(
            jPPesquisaNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPesquisaNomeLayout.createSequentialGroup()
                .addGroup(jPPesquisaNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro do Ingrediente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLID.setText("ID:");

        jLNome.setText("Nome:");

        jLMarca.setText("Marca");

        jLEstoque.setText("Estoque");

        jTNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeActionPerformed(evt);
            }
        });

        jTMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMarcaActionPerformed(evt);
            }
        });

        jTEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEstoqueActionPerformed(evt);
            }
        });

        jBSalvar.setText("SALVAR MODIFICAÇÃO");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLID)
                            .addComponent(jLMarca)
                            .addComponent(jLEstoque))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTNome, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                .addGap(163, 163, 163))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                        .addGap(86, 86, 86))
                                    .addComponent(jTEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(115, 115, 115))))
                    .addComponent(jBSalvar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLID)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMarca)
                    .addComponent(jTMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEstoque))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jBExcluir.setText("EXCLUIR INGREDIENTE");
        jBExcluir.setPreferredSize(new java.awt.Dimension(100, 25));
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBAlterar.setText("ALTERAR DADOS");
        jBAlterar.setPreferredSize(new java.awt.Dimension(100, 25));
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBNovo.setText("CADASTRAR NOVO");
        jBNovo.setPreferredSize(new java.awt.Dimension(100, 25));
        jBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSair)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTIngrediente.setModel(tmIngrediente);
        jTIngrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTIngredienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTIngrediente);

        javax.swing.GroupLayout jPCadFuncionarioLayout = new javax.swing.GroupLayout(jPCadFuncionario);
        jPCadFuncionario.setLayout(jPCadFuncionarioLayout);
        jPCadFuncionarioLayout.setHorizontalGroup(
            jPCadFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPPesquisaNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPCadFuncionarioLayout.setVerticalGroup(
            jPCadFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPCadFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPCadFuncionario.getAccessibleContext().setAccessibleName("CadastroFuncionario");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomeActionPerformed

    private void jTMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMarcaActionPerformed

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed
        limparCampos();
        jTID.setText("");
        habilitaDados();

    }//GEN-LAST:event_jBNovoActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed

        if (verificaDados()){
            novoCadastro();
            limparCampos();
            desabilitaDados();
        }
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        this.dispose();
        //jTFuncionario.
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed

        if (verificaDados()){
            alteraCadastro();
            limparCampos();
            desabilitaDados();
        }
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jTIngredienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTIngredienteMouseClicked

        habilitaDados();
        escolherLinha();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIngredienteMouseClicked

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed

        removerCadastro();

    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisaActionPerformed
        try {
            tmIngrediente.setNumRows(0);
            populaTabela(jTPesquisa.getText());
        } catch (SQLException ex) {
            Logger.getLogger(jFCadIngrediente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBPesquisaActionPerformed

    private void jTEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEstoqueActionPerformed


    public void desabilitarVisaoTodos(){

        //jPFundoCadastro.setVisible(false);
        //jPCadFuncionario.setVisible(false);

    }

    private void escolherLinha(){

        int linha = jTIngrediente.getSelectedRow();
        System.out.println(linha);

        Ingrediente i1 = new Ingrediente();
        String temp;

        temp = String.valueOf(jTIngrediente.getValueAt(linha, 0));
        i1.setId(Integer.parseInt(temp));
        i1.setNome(String.valueOf(jTIngrediente.getValueAt(linha,1)));
        i1.setMarca(String.valueOf(jTIngrediente.getValueAt(linha,2)));
        temp = String.valueOf(jTIngrediente.getValueAt(linha, 3));
        i1.setEstoque(Integer.parseInt(temp));

        escreverJTextField(i1);
        
    }

    private void escreverJTextField(Ingrediente i1){

        System.out.println(i1);

        jTID.setEditable(true);
        jTID.setText(String.valueOf(i1.getId()));
        jTID.setEditable(false);

        jTNome.setText(i1.getNome());
        jTMarca.setText(i1.getMarca());
        jTEstoque.setText(String.valueOf(i1.getEstoque()));

    }
    
    private void novoCadastro(){

        Ingrediente i1 = new Ingrediente();
        i1.setNome(jTNome.getText());
        i1.setMarca(jTMarca.getText());
        i1.setEstoque(Integer.parseInt(jTEstoque.getText()));

         try {
            IngredienteDao dao = new IngredienteDao();
            dao.adiciona(i1);

            tmIngrediente.setNumRows(0);
            populaTabela("");

        } catch (SQLException ex) {
            Logger.getLogger(jFCadIngrediente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void alteraCadastro(){

        Ingrediente f1 = new Ingrediente();
        f1.setId(Integer.parseInt(jTID.getText()));
        f1.setNome(jTNome.getText());
        f1.setMarca(jTMarca.getText());
        f1.setEstoque(Integer.parseInt(jTEstoque.getText()));

        try {
            IngredienteDao dao = new IngredienteDao();
            dao.altera(f1);
            tmIngrediente.setNumRows(0);
            populaTabela("");
        } catch (SQLException ex) {
            Logger.getLogger(jFCadIngrediente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void removerCadastro(){
        
        Ingrediente i1 = new Ingrediente();
        i1.setId(Integer.parseInt(jTID.getText()));
        
        IngredienteDao dao;
        try {
            dao = new IngredienteDao();
            dao.remove(i1);
            tmIngrediente.setNumRows(0);
            populaTabela("");
        } catch (SQLException ex) {
            Logger.getLogger(jFCadIngrediente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void limparCampos(){
        jTID.setText("");
        jTNome.setText("");
        jTMarca.setText("");
        jTEstoque.setText("");
    }

    public void desabilitaDados(){
        jTID.setEditable(false);
        jTNome.setEditable(false);
        jTMarca.setEditable(false);
        jTEstoque.setEditable(false);

    }

    public void habilitaDados(){
        jTNome.setEditable(true);
        jTMarca.setEditable(true);
        jTEstoque.setEditable(true);

    }

    public boolean verificaDados(){

        if (!jTNome.getText().equals("")) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Campo nome não preenchido");
            return false;
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBNovo;
    private javax.swing.JButton jBPesquisa;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JLabel jLEstoque;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLMarca;
    private javax.swing.JLabel jLNome;
    private javax.swing.JPanel jPCadFuncionario;
    private javax.swing.JPanel jPPesquisaNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTEstoque;
    private javax.swing.JTextField jTID;
    private javax.swing.JTable jTIngrediente;
    private javax.swing.JTextField jTMarca;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTPesquisa;
    // End of variables declaration//GEN-END:variables

}
