/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jTFornecedor.java
 *
 * Created on 10/11/2009, 00:49:25
 */

package restaurante.forms;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import restaurantepoo.dao.FornecedorDao;
import restaurantepoo.logica.Fornecedor;

/**
 *
 * @author Fernanda
 */
public class jFCadFornecedor extends javax.swing.JFrame {

    /** Creates new form jTFornecedor */
    public jFCadFornecedor() throws SQLException {
        
        initComponents();
        populaTabela("");
        desabilitaDados();
        desabilitarVisaoTodos();
    }

    DefaultTableModel tmFornecedor = new DefaultTableModel(
            new Object [][]{
            },
            new String[]{"id","cnpj","nome","endereco","telefone","email"});
    
    private List<Fornecedor> fornecedores;
    ListSelectionModel lsmFornecedores;

    public void populaTabela(String busca) throws SQLException{

        FornecedorDao fd = new FornecedorDao();
        fornecedores = fd.getLista("%"+busca+"%");
        
        for (Fornecedor f1 : fornecedores) {
            insereTabela(f1);
        }
    }

    public void insereTabela(Fornecedor f1){

        tmFornecedor.addRow(new String[]{
            String.valueOf(f1.getId()),
            f1.getCnpj(),
            f1.getNome(),
            f1.getEndereco(),
            f1.getTelefone(),
            f1.getEmail(),
        });
    }




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCadFornecedor = new javax.swing.JPanel();
        jPPesquisaNome = new javax.swing.JPanel();
        jBPesquisa = new javax.swing.JButton();
        jTPesquisa = new javax.swing.JTextField();
        jPCadastro = new javax.swing.JPanel();
        jLID = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jLMarca = new javax.swing.JLabel();
        jLEstoque = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jTNome = new javax.swing.JTextField();
        jTEndereco = new javax.swing.JTextField();
        jTCnpj = new javax.swing.JTextField();
        jBSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        jTTelefone = new javax.swing.JTextField();
        jPBotoes = new javax.swing.JPanel();
        jBSair = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFornecedor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(354, 124, 600, 600));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 255));
        setIconImages(null);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPCadFornecedor.setBackground(new java.awt.Color(102, 255, 204));
        jPCadFornecedor.setAlignmentX(0.0F);
        jPCadFornecedor.setAlignmentY(0.0F);
        jPCadFornecedor.setPreferredSize(new java.awt.Dimension(600, 600));

        jPPesquisaNome.setBackground(new java.awt.Color(255, 255, 255));
        jPPesquisaNome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa pelo Nome do Fornecedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPPesquisaNome.setPreferredSize(new java.awt.Dimension(580, 61));

        jBPesquisa.setText("Pesquisa");
        jBPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisaActionPerformed(evt);
            }
        });

        jTPesquisa.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPPesquisaNomeLayout = new javax.swing.GroupLayout(jPPesquisaNome);
        jPPesquisaNome.setLayout(jPPesquisaNomeLayout);
        jPPesquisaNomeLayout.setHorizontalGroup(
            jPPesquisaNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPesquisaNomeLayout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(jTPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPesquisa)
                .addGap(24, 24, 24))
        );
        jPPesquisaNomeLayout.setVerticalGroup(
            jPPesquisaNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPesquisaNomeLayout.createSequentialGroup()
                .addGroup(jPPesquisaNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro do Fornecedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLID.setText("ID:");

        jLNome.setText("Nome:");

        jLMarca.setText("Endereço");

        jLEstoque.setText("CNPJ");

        jTNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeActionPerformed(evt);
            }
        });

        jTEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEnderecoActionPerformed(evt);
            }
        });

        jTCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCnpjActionPerformed(evt);
            }
        });

        jBSalvar.setText("SALVAR MODIFICAÇÃO");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jLabel1.setText("Telefone");

        jLabel2.setText("e-mail");

        jTTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCadastroLayout = new javax.swing.GroupLayout(jPCadastro);
        jPCadastro.setLayout(jPCadastroLayout);
        jPCadastroLayout.setHorizontalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLID)
                    .addComponent(jLMarca)
                    .addComponent(jLEstoque)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addComponent(jTCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                            .addComponent(jTEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLNome)
                                .addGap(18, 18, 18)
                                .addComponent(jTNome, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))
                        .addGap(2, 2, 2))
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jBSalvar))
        );
        jPCadastroLayout.setVerticalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLID)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMarca)
                    .addComponent(jTEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEstoque)
                    .addComponent(jTCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jBExcluir.setText("EXCLUIR FORNECEDOR");
        jBExcluir.setPreferredSize(new java.awt.Dimension(100, 25));
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBAlterar.setText("ALTERAR DADOS");
        jBAlterar.setPreferredSize(new java.awt.Dimension(100, 25));
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBNovo.setText("CADASTRAR NOVO");
        jBNovo.setPreferredSize(new java.awt.Dimension(100, 25));
        jBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBotoesLayout = new javax.swing.GroupLayout(jPBotoes);
        jPBotoes.setLayout(jPBotoesLayout);
        jPBotoesLayout.setHorizontalGroup(
            jPBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPBotoesLayout.setVerticalGroup(
            jPBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSair)
                    .addGroup(jPBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTFornecedor.setModel(tmFornecedor);
        jTFornecedor.getTableHeader().setReorderingAllowed(false);
        jTFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTFornecedor);

        javax.swing.GroupLayout jPCadFornecedorLayout = new javax.swing.GroupLayout(jPCadFornecedor);
        jPCadFornecedor.setLayout(jPCadFornecedorLayout);
        jPCadFornecedorLayout.setHorizontalGroup(
            jPCadFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPBotoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(jPPesquisaNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPCadFornecedorLayout.setVerticalGroup(
            jPCadFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPCadFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPCadFornecedor.getAccessibleContext().setAccessibleName("CadastroFuncionario");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomeActionPerformed

    private void jTEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEnderecoActionPerformed

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed
        limparCampos();
        jTID.setText("");
        habilitaDados();

    }//GEN-LAST:event_jBNovoActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed

        if (verificaDados()){
            novoCadastro();
            limparCampos();
            desabilitaDados();
        }
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        this.dispose();

    }//GEN-LAST:event_jBSairActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed

        if (verificaDados()){
            alteraCadastro();
            limparCampos();
            desabilitaDados();
        }
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jTFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFornecedorMouseClicked

        habilitaDados();
        escolherLinha();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFornecedorMouseClicked

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed

        removerCadastro();

    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisaActionPerformed
        try {
            tmFornecedor.setNumRows(0);
            populaTabela(jTPesquisa.getText());
        } catch (SQLException ex) {
            Logger.getLogger(jFCadFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBPesquisaActionPerformed

    private void jTCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCnpjActionPerformed

    private void jTTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTelefoneActionPerformed


    public void desabilitarVisaoTodos(){

        //jPFundoCadastro.setVisible(false);
        //jPCadFuncionario.setVisible(false);

    }

    private void escolherLinha(){

        int linha = jTFornecedor.getSelectedRow();

        Fornecedor f1 = new Fornecedor();
        String temp;

            temp = String.valueOf(jTFornecedor.getValueAt(linha, 0));
        f1.setId(Integer.parseInt(temp));
        f1.setCnpj(String.valueOf(jTFornecedor.getValueAt(linha, 1)));
        f1.setNome(String.valueOf(jTFornecedor.getValueAt(linha, 2)));
        f1.setEndereco(String.valueOf(jTFornecedor.getValueAt(linha, 3)));
        f1.setTelefone(String.valueOf(jTFornecedor.getValueAt(linha, 4)));
        f1.setEmail(String.valueOf(jTFornecedor.getValueAt(linha, 5)));

        escreverJTextField(f1);
        
    }

    private void escreverJTextField(Fornecedor f1){

        jTID.setEditable(true);
        jTID.setText(String.valueOf(f1.getId()));
        jTID.setEditable(false);

        jTNome.setText(f1.getNome());
        jTEndereco.setText(f1.getEndereco());
        jTCnpj.setText(f1.getCnpj());
        jTTelefone.setText(f1.getTelefone());
        jTEmail.setText(f1.getEmail());
    }
    
    private void novoCadastro(){

        Fornecedor f1 = new Fornecedor();
        f1.setNome(jTNome.getText());
        f1.setEndereco(jTEndereco.getText());
        f1.setCnpj(jTCnpj.getText());
        f1.setTelefone(jTTelefone.getText());
        f1.setEmail(jTEmail.getText());


         try {
            FornecedorDao dao = new FornecedorDao();
            dao.adiciona(f1);

            tmFornecedor.setNumRows(0);
            populaTabela("");

        } catch (SQLException ex) {
            Logger.getLogger(jFCadFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void alteraCadastro(){

        Fornecedor f1 = new Fornecedor();
        f1.setId(Integer.parseInt(jTID.getText()));
        f1.setNome(jTNome.getText());
        f1.setCnpj(jTCnpj.getText());
        f1.setEndereco(jTEndereco.getText());
        f1.setTelefone(jTTelefone.getText());
        f1.setEmail(jTEmail.getText());

        try {
            FornecedorDao dao = new FornecedorDao();
            dao.altera(f1);
            tmFornecedor.setNumRows(0);
            populaTabela("");
        } catch (SQLException ex) {
            Logger.getLogger(jFCadFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void removerCadastro(){
        
        Fornecedor f1 = new Fornecedor();
        f1.setId(Integer.parseInt(jTID.getText()));
        
        try {
            FornecedorDao dao = new FornecedorDao();
            dao.remove(f1);
            tmFornecedor.setNumRows(0);
            populaTabela("");
        } catch (SQLException ex) {
            Logger.getLogger(jFCadFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void limparCampos(){
        jTID.setText("");
        jTNome.setText("");
        jTEndereco.setText("");
        jTCnpj.setText("");
        jTTelefone.setText("");
        jTEmail.setText("");
    }

    public void desabilitaDados(){
        jTID.setEditable(false);
        jTNome.setEditable(false);
        jTEndereco.setEditable(false);
        jTCnpj.setEditable(false);
        jTTelefone.setEditable(false);
        jTEmail.setEditable(false);

    }

    public void habilitaDados(){
        jTNome.setEditable(true);
        jTEndereco.setEditable(true);
        jTCnpj.setEditable(true);
        jTTelefone.setEditable(true);
        jTEmail.setEditable(true);

    }

    public boolean verificaDados(){

        if (!jTNome.getText().equals("")) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Campo nome não preenchido");
            return false;
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBNovo;
    private javax.swing.JButton jBPesquisa;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JLabel jLEstoque;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLMarca;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPBotoes;
    private javax.swing.JPanel jPCadFornecedor;
    private javax.swing.JPanel jPCadastro;
    private javax.swing.JPanel jPPesquisaNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCnpj;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTEndereco;
    private javax.swing.JTable jTFornecedor;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTPesquisa;
    private javax.swing.JTextField jTTelefone;
    // End of variables declaration//GEN-END:variables

}
